#!/bin/bash

# pluginadm
#
# Automatically deploy applications in smartos in a semi-interactive way
# Application set up scripts are packages as "plugins", thus pluginadm

IFS=$'\n'

case "$1" in

"install")
	/opt/.pluginadm/install.sh $2
	
	if [ "$?" -ne "0" ]; then
		exit 1
	fi
	;;
	
"avail")
	echo "Name^Description" > /tmp/avail.txt
	for FILE in `find /opt/.pluginadm/recipes/*`; do 
		source $FILE
		echo "$name^$description" >> /tmp/avail.txt
	done
	column -t -s ^ /tmp/avail.txt
	rm /tmp/avail.txt
	;;

"setup") echo "Not Yet Implemented"
	exit 1
	;;

"update")
	/opt/.pluginadm/update.sh
	if [ "$?" = 0 ]; then 
		echo "Update Successful" 
	else 
		echo "Update Failed: Something has not gone well"
	fi
	;;

""|help)
	case $2 in

	"install")
		echo "Usage:"
		echo "pluginadm install <plugin>"
		echo ""
		echo "Install specified plugin"
		;;

	"avail")
		echo "Usage:"
		echo "pluginadm avail"
		echo ""
		echo "List available plugins"
		;;

	"setup")
		echo "Not Yet Implemented"
		;;

	"update")
		echo "Not Yet Implemented"
		;;

	*)
		echo "Usage:"
		echo "pluginadm <command> [options]"
		echo ""
		echo "install <application>"
		echo "avail"
		echo "setup"
		echo "help" [command]
		exit 0
		;;
	
	esac
esac
